### ISSUE TITLE
Risk of unable to acquire a lock?

### ISSUE THREAD

**Issue by kingiw** [EagleChen/mapmutex#1]
https://github.com/EagleChen/mapmutex/blob/e1a5ae258d8dfac26e70851e6098f6d34f480c06/mutex.go#L23

It seems there are risks that the loop terminates and cannot acquire the lock (where `TryLock` returns false).

What if we turn the loop to be an infinite loop, only return when the lock is acquired?

**Comment by EagleChen** [comment]
It's better to let the caller decide how long to wait (how many times to retry).

you can set a very large `maxRetry` or try to call `tryLock` as many times as you want (this is shown in README)
